name: Lint PR

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v4.3.0
